name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: echo github
        run: |
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.workspace }}
      - name: Build project
        run: mvn -B package --file pom.xml
      - name: Archive jar
        uses: actions/upload-artifact@v1
        with:
          name: mybatis-demo-${{ github.ref }}.jar
          path: target/mybatis-demo-${{ github.ref }}.jar